[package]
name = "stream"
description = "MTProto stream worker pool, chunk cache, and byte-range stream engine."
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ferogram.workspace = true
db = { path = "../db" }
music = { path = "../music" }
tokio.workspace = true
bytes.workspace = true
futures-util.workspace = true
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
sha2.workspace = true
moka.workspace = true
chrono.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread", "time", "test-util"] }

[lints]
workspace = true
