[package]
name = "server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
tower.workspace = true
tower-http.workspace = true
utoipa.workspace = true
hmac.workspace = true
sha2.workspace = true
tokio.workspace = true
tokio-util.workspace = true
futures-util.workspace = true
bytes.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
rand.workspace = true
base64.workspace = true
moka.workspace = true
cuid2.workspace = true

reqwest = { workspace = true, features = ["json"] }

music = { path = "../music" }
apple = { path = "../apple" }
lyrics = { path = "../lyrics", features = ["lrclib", "betterlyrics", "paxsenix"] }
engine = { path = "../engine" }
db = { path = "../db" }
stream = { path = "../stream" }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
dotenvy.workspace = true
ferogram.workspace = true

[lints]
workspace = true
